### ISSUE TITLE
Android build?

### ISSUE THREAD

**Issue by pimpaa** [chilipeppr/serial-port-json-server#22]
Is it possible to build for Android devices?

**Comment by chilipeppr** [comment]
Give it a try. It may be if Go is supported there.

**Comment by pimpaa** [comment]
I'm gonna give it a try later. Also, was wondering what would be the best way to run as a service on Windows, do you have any idea?

**Comment by chilipeppr** [comment]
There's a bunch of articles online about how to turn a command line app
into a Windows service.

**Comment by chilipeppr** [comment]
There's also a lot of examples of how folks have created Windows service
apps in Go that would be a nice addition to SPJS. I'd welcome a pull
request on that one.

**Comment by pimpaa** [comment]
Thanks a lot for the reply! Going to look at the forks, didn't think about that.
