### ISSUE TITLE
No 'Access-Control-Allow-Origin' header from localhost to localhost

### ISSUE THREAD

**Issue by binaryangel-noah** [chilipeppr/serial-port-json-server#53]
Hallo,

i am calling the server on localhost and get the following response: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access

And websocket returns always 404.

**Comment by chilipeppr** [comment]
That sounds to me like you're not connecting to a websocket, rather you're
trying to do an HTTP ajax call?

**Comment by binaryangel-noah** [comment]
I am trying both.
